name: Prymal Shopify Inventory Report
run-name: ${{ github.actor }} - Shopify Inventory Report 
on: 
  push:
    paths:
      - '**/extraction/**'
      - '**/workflows/prymal_shopify_inventory_report_extraction.yml'
  schedule:
    - cron: '0 10 * * *'  # Runs at 10 AM every day
jobs:
  shipbob_inventory_etl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r extraction/requirements.txt
    
      - name: Generate Shopify Inventory Report
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          S3_PRYMAL_ANALYTICS: ${{ secrets.S3_PRYMAL_ANALYTICS }}
        run: python extraction/shopify_inventory_report.py 

      # - name: Run Shopify Glue Crawlers
      #   env: 
      #     AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
      #   run: python crawlers/shipbob_inventory/shipbob_inventory_crawler.py 
        

      - run: echo "Job status - ${{ job.status }}."
